"""
AI Report Service — generates daily narrative reports using GPT-4o-mini.

Takes computed behavioral metrics and produces a human-readable report
with insights, motivational messaging, and behavioral observations.

Architecture:
  AnalyticsService → computes all metrics (pure Python, no LLM)
  ReportService    → calls generate_daily_report() with those metrics
  generate_daily_report() → structured LLM call → DailyReport.insights_text

Using GPT-4o-mini here (not full GPT-4o):
  - Reports are text-only, no vision needed
  - Generated daily — cost matters
  - The prompts are data-rich enough that mini performs very well
  - If quality is poor in practice, swap to gpt-4o in config

Tone styles:
  motivational — High energy, celebrate wins, positive reframe of misses
  analytical   — Data-focused, precise, trend references, actionable
  brief        — Bullet points, 3-5 sentences max, fast to read
  detailed     — Comprehensive, educational, explains the why behind patterns
"""
from dataclasses import dataclass, field
from datetime import date
from typing import Literal

from pydantic import BaseModel

from app.config import settings
from app.core.exceptions import ExternalServiceError
from app.core.logging import get_logger
from app.services.ai.client import get_openai_client

logger = get_logger(__name__)

REPORT_MODEL = "gpt-4o-mini"

# ── Input Data ─────────────────────────────────────────────────────────────────

@dataclass
class ReportContext:
    """All computed data needed to generate a daily report."""
    report_date: date
    report_style: Literal["motivational", "analytical", "brief", "detailed"]

    # User profile
    goal: str                        # lose_weight | maintain | gain_muscle | improve_fitness
    target_calories: float | None
    target_protein_g: float | None

    # Today's nutrition
    actual_calories: float
    actual_protein_g: float
    actual_carbs_g: float
    actual_fat_g: float
    meals_logged: int

    # Today's workouts
    workouts_completed: int
    total_calories_burned: float
    workout_types: list[str] = field(default_factory=list)
    workout_duration_minutes: float = 0.0

    # Streak and consistency
    streak_days: int = 0
    consistency_7d: float = 0.0      # 0.0–1.0
    calorie_adherence_7d: float = 0.0
    protein_adherence_7d: float = 0.0

    # Pattern-based observations (generated by AnalyticsService)
    # These are passed in already computed — LLM only narrates, doesn't compute
    behavioral_patterns: list[str] = field(default_factory=list)

    # Recent correction rate (tells us about user engagement + AI quality)
    correction_rate_pct: float = 0.0


# ── Structured Output ──────────────────────────────────────────────────────────

class _ReportOutput(BaseModel):
    """Structured output from the report LLM call."""
    insights_text: str          # 2-4 paragraph narrative
    motivation_message: str     # 1-2 sentences, closing motivational message
    behavioral_observations: list[str]  # 2-5 specific, data-backed observations


# ── Style Guidance ─────────────────────────────────────────────────────────────

_STYLE_GUIDANCE = {
    "motivational": (
        "Use high-energy, celebratory language. Lead with wins. Reframe any misses "
        "as opportunities. Use exclamation points sparingly but effectively. "
        "Make the user feel proud and motivated to continue tomorrow."
    ),
    "analytical": (
        "Be precise and data-focused. Reference specific numbers. Identify trends. "
        "Explain why something happened based on the data. Keep emotional language minimal. "
        "Focus on actionable insights the user can apply tomorrow."
    ),
    "brief": (
        "Be extremely concise. Maximum 3 sentences for insights_text. "
        "Use bullet points where possible. Cut all filler words. "
        "Every word must earn its place. Think executive summary."
    ),
    "detailed": (
        "Be comprehensive and educational. Explain the reasoning behind each observation. "
        "Reference both today's data and weekly trends. Include context about why "
        "these patterns matter for the user's goal. Aim for 4-5 substantive paragraphs."
    ),
}

_SYSTEM_PROMPT = """
You are an expert fitness coach generating a personalized daily progress report.
Your reports are data-driven, encouraging, and actionable.

RULES:
- No medical advice or health diagnoses whatsoever
- Be honest about missed targets but always remain constructive
- Reference the actual data provided — never invent numbers
- Keep insights specific to this user's goal and today's performance
- Behavioral observations should be pattern-based (use phrases like "you tend to"
  or "on days like today") — never absolute ("you always" / "you never")
- Maximum 5 behavioral observations
""".strip()


# ── Report Generation ──────────────────────────────────────────────────────────

async def generate_daily_report(ctx: ReportContext) -> _ReportOutput:
    """
    Generate a structured daily report using GPT-4o-mini.

    Args:
        ctx: All computed behavioral metrics for the day

    Returns:
        _ReportOutput with insights_text, motivation_message, behavioral_observations

    Raises:
        ExternalServiceError if the API call fails
    """
    style_guide = _STYLE_GUIDANCE.get(ctx.report_style, _STYLE_GUIDANCE["motivational"])

    # Compute derived values for the prompt
    calorie_pct = (
        round((ctx.actual_calories / ctx.target_calories) * 100)
        if ctx.target_calories and ctx.target_calories > 0
        else None
    )
    net_calories = ctx.actual_calories - ctx.total_calories_burned
    is_rest_day = ctx.workouts_completed == 0

    workout_text = (
        f"{ctx.workouts_completed} workout(s): {', '.join(ctx.workout_types)} "
        f"({ctx.workout_duration_minutes:.0f} min, {ctx.total_calories_burned:.0f} kcal burned)"
        if not is_rest_day
        else "Rest day — no workouts logged"
    )

    protein_status = ""
    if ctx.target_protein_g and ctx.target_protein_g > 0:
        prot_pct = round((ctx.actual_protein_g / ctx.target_protein_g) * 100)
        protein_status = f"Protein: {ctx.actual_protein_g:.0f}g / {ctx.target_protein_g:.0f}g target ({prot_pct}%)"
    else:
        protein_status = f"Protein: {ctx.actual_protein_g:.0f}g logged"

    calorie_line = (
        f"Calories: {ctx.actual_calories:.0f} kcal"
        + (f" / {ctx.target_calories:.0f} kcal target ({calorie_pct}%)" if calorie_pct else "")
    )

    patterns_text = (
        "\n".join(f"- {p}" for p in ctx.behavioral_patterns)
        if ctx.behavioral_patterns
        else "- No strong patterns detected yet (keep logging to build history)"
    )

    user_prompt = f"""
Generate a daily fitness report for {ctx.report_date.strftime('%A, %B %d, %Y')}.

REPORT STYLE: {ctx.report_style.upper()}
Style guidance: {style_guide}

USER'S GOAL: {ctx.goal.replace('_', ' ').title()}

TODAY'S NUTRITION:
- {calorie_line}
- Net calories (after workouts): {net_calories:.0f} kcal
- {protein_status}
- Carbs: {ctx.actual_carbs_g:.0f}g | Fat: {ctx.actual_fat_g:.0f}g
- Meals logged: {ctx.meals_logged}

TODAY'S ACTIVITY:
- {workout_text}

CONSISTENCY CONTEXT:
- Current logging streak: {ctx.streak_days} day(s)
- 7-day logging consistency: {ctx.consistency_7d * 100:.0f}%
- 7-day calorie adherence: {ctx.calorie_adherence_7d * 100:.0f}%
- 7-day protein adherence: {ctx.protein_adherence_7d * 100:.0f}%
- AI estimate correction rate: {ctx.correction_rate_pct:.0f}% (how often estimates were adjusted)

DETECTED BEHAVIORAL PATTERNS (use these in your observations):
{patterns_text}

Generate the report now. Be specific, be data-driven, be encouraging.
""".strip()

    client = get_openai_client()

    logger.info(
        "report_generation_started",
        report_date=str(ctx.report_date),
        style=ctx.report_style,
        streak=ctx.streak_days,
    )

    try:
        response = await client.beta.chat.completions.parse(
            model=REPORT_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            response_format=_ReportOutput,
            temperature=0.7,    # Some creativity for engaging narratives
            max_tokens=800,
        )
    except Exception as e:
        logger.error("report_generation_api_error", error=str(e))
        raise ExternalServiceError(
            message="Report generation service temporarily unavailable",
            service="openai_report",
        ) from e

    result = response.choices[0].message.parsed
    if result is None:
        raise ExternalServiceError(
            message="AI returned an empty response for daily report",
            service="openai_report",
        )

    logger.info(
        "report_generation_complete",
        observations_count=len(result.behavioral_observations),
        tokens_used=response.usage.total_tokens if response.usage else 0,
    )

    return result
